<?php

namespace FiveMinTo\BurgerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BurgerIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BurgerIngredientRepository extends EntityRepository
{
}