<?php

namespace FiveMinTo\BurgerBundle\Entity;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * BurgerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BurgerRepository extends EntityRepository
{
	/*
	 * Get best burger according the vote
	 */
	public function getBestBurger(){
		
		$query = $this->_em->createQuery('SELECT b FROM FiveMinToBurgerBundle:Burger b WHERE b.id=1');
		$results = $query->getResult();
		foreach($results as $result){
			$result->getAttribut();
		}
		
		return $results;
	}
	
	
	
	
}
