five_min_to_burger_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FiveMinToBurgerBundle:Default:index }

<<<<<<< HEAD
five_min_to_burger_bundle: 
    resource: "@FiveMinToBurgerBundle/Controller/" 
    type:     annotation 
=======

five_min_to_burger_bundle: 
    resource: "@FiveMinToBurgerBundle/Controller/" 
    type:     annotation 
    
five_min_to_burger_display_burger:
    pattern:  /displayBurger
    defaults: { _controller: FiveMinToBurgerBundle:DisplayBurger:displayBurger }
    
five_min_to_burger_besty_burger:
    pattern:  /bestBurger
    defaults: { _controller: FiveMinToBurgerBundle:BestBurger:bestBurger }
    
five_min_to_burger_remove_burger:
    pattern:  /removeBurger
    defaults: { _controller: FiveMinToBurgerBundle:RemoveBurger:removeBurger }
>>>>>>> db54261911217ec130a3d32538f992e42e7b780e
