five_min_to_burger_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FiveMinToBurgerBundle:Default:index }

five_min_to_burger_bundle: 
    resource: "@FiveMinToBurgerBundle/Controller/" 
    type:     annotation 
